Repository bigskysoftware/htmx, pull requests merged in 2023-07, with the labels that each got.

#1591 [Bugfix] Fix ie11 incompatible syntax
  src/htmx.js
Labels: bug, ready for review

#1589 Remove engine from package.json
  package.json
Labels: bug, ready for review

#1586 Fix: `hx-on` event listener clean-up
  src/htmx.js
Labels: bug, ready for review

#1600 Add tests for HX Retarget and fix typo
  src/ext/response-targets.js
  test/ext/response-targets.js
Labels: bug, ready for review

#1567 [Bugfix] Handle dynamically added hx-disable
  src/htmx.js
  test/core/security.js
Labels: bug, ready for review

#1479 [New feature] Comma separated list syntax for HX-Trigger response header
  src/htmx.js
  test/core/headers.js
  www/content/headers/hx-trigger.md
Labels: enhancement, ready for review

#1609 Update hx-trigger throttle documentation
  www/content/attributes/hx-trigger.md
Labels: documentation

#1563 [Bugfix] Fix references to element.id
  src/htmx.js
Labels: bug, ready for review

#1571 [Bugfix] Fix hx-trigger `changed` modifier along `from` clause
  src/htmx.js
  test/attributes/hx-trigger.js
Labels: bug, ready for review

#1559 [Bugfix] Fix submit buttons/inputs handling
  src/htmx.js
  test/core/ajax.js
  test/ext/ws.js
Labels: bug, ready for review

#1628 Fixed typo in websockets documentation
  www/content/extensions/web-sockets.md
Labels: documentation

#1530 Update podcasts.csv
  www/content/talk/podcasts.csv
Labels: website, under discussion
