Repository bigskysoftware/htmx, pull requests merged in 2023-12, with the labels that each got.

#2049 Fix form validation docs example
  www/content/docs.md
Labels: documentation

#2045 Improve performance of lib during initialization phase
  src/htmx.js
Labels: ready for review, performance

#1540 Cache evaluated trigger specs
  src/htmx.js
Labels: ready for review, performance

#1307 add extension to populate path variables with request parameters
  src/ext/path-params.js
  test/ext/path-params.js
  test/index.html
  www/content/extensions/_index.md
  www/content/extensions/path-params.md
Labels: extension, ready for review

#2091 Prevent references to nodes swapped out of the dom accumulating as detached elements in memory
  src/htmx.js
Labels: performance

#2095 Remove legacy WS/SSE code
  src/ext/sse.js
  src/htmx.js
  test/attributes/hx-sse.js
  test/attributes/hx-ws.js
  test/ext/sse.js
  test/index.html
  test/ws-sse/static/site-base.html
  test/ws-sse/static/sse-multichannel-ext.html
  test/ws-sse/static/sse-multichannel.html
  test/ws-sse/static/sse-multiple-ext.html
  test/ws-sse/static/sse-multiple.html
  test/ws-sse/static/sse-settle-ext.html
  test/ws-sse/static/sse-settle.html
  test/ws-sse/static/sse-simple-ext.html
  test/ws-sse/static/sse-simple.html
  test/ws-sse/static/sse-target-ext.html
  test/ws-sse/static/sse-target.html
  test/ws-sse/static/sse-triggers-ext.html
  test/ws-sse/static/sse-triggers.html
  test/ws-sse/static/ws-echo-ext.html
  test/ws-sse/static/ws-echo.html
  test/ws-sse/static/ws-heartbeat-ext.html
  test/ws-sse/static/ws-heartbeat.html
  test/ws-sse/static/ws-reconnect.html
Labels: 2.0

#2024 Improve head tag parsing on template fragments
  src/htmx.js
  test/manual/hxboost_partial_template_parsing/index-partial.html
  test/manual/hxboost_partial_template_parsing/index.html
  test/manual/hxboost_partial_template_parsing/other-content.html
  test/manual/index.html
Labels: ready for review

#2017 rewrite the HX-Retarget header to use extended query selectors
  src/htmx.js
Labels: ready for review

#1835 Update parseInterval to handle "0" correctly
  src/htmx.js
  test/attributes/hx-swap.js
  test/attributes/hx-trigger.js
  test/core/internals.js
Labels: bug, ready for review

#2119 Removed outdated note in oob swap documentation
  www/content/attributes/hx-swap-oob.md
  www/content/docs.md
Labels: documentation

#2120 Support encapsulating oob swap elements in templates in response
  src/htmx.js
  test/attributes/hx-swap-oob.js
  www/content/attributes/hx-swap-oob.md
Labels: 2.0

#2123 Enable Node CI for v2.0v2.0 branch
  .github/workflows/ci.yml
Labels: devops, 2.0

#2122 Updated mocha, tests now work with node 20
  .github/workflows/ci.yml
  package-lock.json
  package.json
  test/core/headers.js
  test/core/internals.js
  test/core/perf.js
  test/index.html
Labels: devops, 2.0
