Repository bigskysoftware/htmx, pull requests merged in 2023-09, with the labels that each got.

#1670 Add example of how to structure binary-data forms without data loss
  www/content/docs.md
  www/content/examples/_index.md
  www/content/examples/file-upload-input.md
Labels: documentation

#1742 Use raw attribute href on hx-boost
  src/htmx.js
  test/attributes/hx-disinherit.js
Labels: bug, ready for review

#1687 Make htmx IE11 compatible again + tests IE11 compatible
  package-lock.json
  package.json
  src/ext/loading-states.js
  src/ext/morphdom-swap.js
  src/htmx.js
  test/attributes/hx-disinherit.js
  test/core/ajax.js
  test/core/events.js
  test/core/internals.js
  test/core/perf.js
  test/core/regressions.js
  test/core/validation.js
  test/ext/hyperscript.js
  test/ext/ws.js
  test/index.html
  test/util/util.js
Labels: bug

#1770 Add `allowScriptTags` to docs
  www/content/api.md
Labels: documentation

#1777 Support formaction and formmethod on <button>
  src/htmx.js
  test/attributes/hx-boost.js
Labels: enhancement, ready for review

#1776 Add support for array templates to the client-side templates extension
  src/ext/client-side-templates.js
  test/ext/client-side-templates.js
  www/content/extensions/client-side-templates.md
Labels: enhancement, ready for review

#1721 Make htmx.ajax always return a Promise
  src/htmx.d.ts
  src/htmx.js
Labels: bug, ready for review

#1650 Allow disable-element extension to disable multiple elements
  src/ext/disable-element.js
  test/ext/disable-element.js
  www/content/extensions/disable-element.md
Labels: enhancement, ready for review

#1455 Allow hx-swap options to be used without specifying modifier (innerHTML remains the default)
  src/htmx.js
  test/attributes/hx-swap.js
  www/content/attributes/hx-swap.md
Labels: ready for review

#1453 Support event names with "." character
  src/htmx.js
  test/attributes/hx-on.js
Labels: enhancement, ready for review

#1210 Extend client-side-templates to handle XSLT transformations
  src/ext/client-side-templates.js
  test/ext/client-side-templates.js
  www/content/extensions/_index.md
  www/content/extensions/client-side-templates.md
Labels: ready for review

#1815 [Test] Add a test to ensure inputs outside form with `form` attribute work properly
  test/core/ajax.js
Labels: ready for review

#1371 Fix swapError with hx-on and innerHTML swap
  test/attributes/hx-on-wildcard.js
  test/attributes/hx-on.js
Labels: ready for review

#1813 Add version number to test page
  test/index.html
  www/static/test/index.html
Labels: website, ready for review

#1818 [Tests] Fix test pipeline timing issues
  test/core/ajax.js
  test/core/parameters.js
  test/core/security.js
  test/index.html
Labels: ready for review, devops

#1456 Add support for event cancellation (preventDefault) in extensions
  src/htmx.js
  test/core/extensions.js
  test/index.html
Labels: enhancement, ready for review

#1829 [Documentation] Mention no dist push in contribution guidelines
  CONTRIBUTING.md
Labels: documentation, ready for review

#1814 Add another Elixir example to server-examples.md
  www/content/server-examples.md
Labels: documentation, ready for review

#1765 Update Ruby list of server-examples.md
  www/content/server-examples.md
Labels: documentation, ready for review
