Repository bigskysoftware/htmx, pull requests merged in 2023-08, with the labels that each got.

#1654 Add date and author to essay template
  www/config.toml
  www/content/essays/10-tips-for-SSR-HDA-apps.md
  www/content/essays/_index.md
  www/content/essays/a-real-world-react-to-htmx-port.md
  www/content/essays/a-response-to-rich-harris.md
  www/content/essays/architectural-sympathy.md
  www/content/essays/complexity-budget.md
  www/content/essays/hateoas.md
  www/content/essays/how-did-rest-come-to-mean-the-opposite-of-rest.md
  www/content/essays/hypermedia-apis-vs-data-apis.md
  www/content/essays/hypermedia-clients.md
  www/content/essays/hypermedia-driven-applications.md
  www/content/essays/hypermedia-friendly-scripting.md
  www/content/essays/hypermedia-on-whatever-youd-like.md
  www/content/essays/locality-of-behaviour.md
  www/content/essays/rest-copypasta.md
  www/content/essays/spa-alternative.md
  www/content/essays/splitting-your-apis.md
  www/content/essays/template-fragments.md
  www/content/essays/two-approaches-to-decoupling.md
  www/content/essays/view-transitions.md
  www/content/essays/when-to-use-hypermedia.md
  www/themes/htmx-theme/static/css/site.css
  www/themes/htmx-theme/templates/essay.html
  www/themes/htmx-theme/templates/page.html
Labels: website, ready for review

#1648 Tighten up hx-on docs
  www/content/attributes/hx-on.md
Labels: documentation, ready for review

#1656 Update same site security to use origin
  src/htmx.js
Labels: bug, ready for review

#1545 [Performance] Fast path to resolve body selector
  src/htmx.js
Labels: enhancement, ready for review

#1111 Cleaner Bootstrap 5 modals example.
  www/content/examples/modal-bootstrap.md
Labels: documentation, ready for review

#1629 Support hx-target-5xx syntax in response-targets extension
  src/ext/response-targets.js
  test/ext/response-targets.js
  www/content/extensions/response-targets.md
Labels: enhancement

#1657 Remove logAll from tests
  test/core/security.js
Labels: devops

#1677 Move load tests to the bottom of the core file
  test/core/api.js
Labels: ready for review, devops

#1688 Track DOM content loaded for ready() function
  src/htmx.js
Labels: bug, ready for review

#1674 [websocket] pass hx-target id in the HEADERS
  src/ext/ws.js
  test/ext/ws.js
Labels: enhancement, extension, ready for review

#1682 Fix hx-on/hx-on:* to suppress evaluation if allowEval is false
  src/htmx.js
  test/attributes/hx-on-wildcard.js
  test/attributes/hx-on.js
  test/attributes/hx-vals.js
  test/attributes/hx-vars.js
Labels: bug, ready for review

#1705 Add "Why htmx Doesn't Have a Build Step" essay
  www/content/essays/_index.md
  www/content/essays/no-build-step.md
Labels: website, ready for review

#1719 Fix typo in attribute
  CHANGELOG.md
Labels: documentation

#1737 Expand contribution guidelines to separate file
  CONTRIBUTING.md
  README.md
Labels: devops

#1741 Update preload extension docs
  www/content/extensions/preload.md
Labels: documentation
