Repository bigskysoftware/htmx, pull requests merged in 2023-11, with the labels that each got.

#1459 Add config option to disable scroll into view for targets of boosted links and forms
  src/htmx.js
  www/content/api.md
  www/content/attributes/hx-swap.md
Labels: enhancement, under discussion

#1961 Add htmx/elem-go server examples
  www/content/server-examples.md
Labels: website

#1522 List extended selectors + caveats in hx-include doc
  www/content/attributes/hx-include.md
Labels: documentation, under discussion

#1970 Add new config options to typescript defs
  src/htmx.d.ts
Labels: ready for review

#1952 Replace keyup with input event
  www/content/examples/active-search.md
Labels: documentation

#1983 Fix link on scaling essay
  www/content/essays/does-hypermedia-scale.md
Labels: website, ready for review

#1973 Homogenize configuration docs
  www/content/api.md
  www/content/docs.md
Labels: documentation, ready for review

#1927 Add configuration options list to reference docs
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#1986 Add config option scrollIntoViewOnBoost to typescript defs
  src/htmx.d.ts
Labels: ready for review

#1985 Add `select` option to htmx.ajax()
  src/htmx.d.ts
  src/htmx.js
  test/core/api.js
  www/content/api.md
Labels: ready for review

#1981 Fix missing ignoreTitle property declaration in htmx.config
  dist/htmx.d.ts
  src/htmx.js
Labels: ready for review

#1980 Add a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review

#1943 Update contribution guidelines
  CONTRIBUTING.md
Labels: ready for review

#1906 Allow user to override Content-Type header
  src/htmx.js
  test/core/api.js
Labels: bug, ready for review

#1913 Allow CSS selectors with whitespace in `hx-trigger`
  src/htmx.js
  test/attributes/hx-trigger.js
  www/content/attributes/hx-trigger.md
Labels: enhancement, ready for review

#1227 fix indicator styles flash
  src/htmx.js
Labels: bug, ready for review

#1949 Fix WS sendImmediately
  src/ext/ws.js
  test/ext/ws.js
Labels: bug, ready for review

#1960 Fix relative resource URLs for boosted links
  src/htmx.js
  test/attributes/hx-boost.js
  test/manual/hxboost_relative_resources/index.html
  test/manual/hxboost_relative_resources/nested/img.png
  test/manual/hxboost_relative_resources/nested/page2.html
  test/manual/index.html
Labels: bug, under discussion

#1972 Fix for race condition in readystate detection
  src/htmx.js
Labels: ready for review

#2020 Fix hx-on anchor in the docs
  www/content/docs.md
Labels: documentation

#2035 Update server-examples.md
  www/content/server-examples.md
Labels: documentation

#2039 Removed IE-specific tests
  test/core/ajax.js
  test/core/events.js
  test/core/extensions.js
  test/core/internals.js
  test/core/perf.js
  test/core/regressions.js
  test/core/validation.js
  test/ext/hyperscript.js
  test/ext/ws.js
  test/index.html
  test/util/util.js
Labels: 2.0
