Repository bigskysoftware/htmx, pull requests merged in 2023-10, with the labels that each got.

#1847 Update file-upload.md
  www/content/examples/file-upload.md
Labels: documentation

#1846 Update docs.md
  www/content/docs.md
Labels: documentation

#1838 Fix reference in notes from `hx-disable-elts` to `hx-disable-elt`
  www/content/attributes/hx-disabled-elt.md
Labels: documentation

#1839 Improve request/response documentation in docs.md
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#1867 Ignore formmethod when value is "dialog"
  src/htmx.js
  test/core/ajax.js
Labels: bug, ready for review

#1836 Fix Handlebars template rendering
  src/ext/client-side-templates.js
  test/ext/client-side-templates.js
  www/content/extensions/client-side-templates.md
Labels: bug, ready for review

#1785 Clear lastButtonClicked ref if it was removed from the DOM
  src/htmx.js
Labels: bug, ready for review

#1573 Add new event htmx:beforeHistoryUpdate
  src/htmx.js
  www/content/events.md
Labels: enhancement, ready for review

#1478 [New feature] selector-less next and previous targets
  src/htmx.js
  test/attributes/hx-target.js
  test/attributes/hx-trigger.js
  test/util/util.js
  www/content/attributes/hx-target.md
  www/content/attributes/hx-trigger.md
Labels: enhancement, ready for review

#1907 Fixed indentation/rendering in Modal bootstrap example page
  www/content/examples/modal-bootstrap.md
Labels: documentation

#1908 Fixed ws and sse references in the docs
  www/content/attributes/hx-sse.md
  www/content/attributes/hx-ws.md
  www/content/extensions/server-sent-events.md
  www/content/extensions/web-sockets.md
Labels: documentation

#1917 Fix: form submission of email inputs with `multiple` attribute
  src/htmx.js
  test/core/ajax.js
Labels: bug, ready for review

#1903 Fix websocket polling trigger
  src/ext/ws.js
  test/ext/ws.js
Labels: ready for review

#1902 Fix: Use getElementById instead of querySelector to work with all valid characters
  src/htmx.js
Labels: bug, ready for review

#1610 Fix `confirmed` being ignored in htmx:confirm event
  src/htmx.js
  test/attributes/hx-confirm.js
  test/core/events.js
  test/index.html
  www/content/attributes/hx-confirm.md
  www/content/examples/confirm.md
Labels: enhancement, ready for review

#1894 fix: prevent nodeData.onHandlers overwrite
  src/htmx.js
  test/attributes/hx-on-wildcard.js
  test/attributes/hx-on.js
Labels: bug, ready for review

#1222 Clear cache when historyCacheSize is set to 0
  src/htmx.js
Labels: bug, ready for review

#1929 Add hx-target-error attribute to response-targets extension
  src/ext/response-targets.js
  www/content/extensions/response-targets.md
Labels: ready for review

#1936 Add missing config settings to type declarations in dist/htmx.d.ts
  dist/htmx.d.ts
Labels: ready for review

#1820 Fix stale form references
  src/htmx.js
  test/core/ajax.js
Labels: bug, ready for review
