Repository bigskysoftware/htmx, pull requests merged in 2024-11, with the labels that each got.

#2991 Added Jeasx example for template fragements
  www/content/essays/template-fragments.md
Labels: documentation

#3002 Add Next.js to htmx essay
  www/content/essays/_index.md
  www/content/essays/a-real-world-nextjs-to-htmx-port.md
Labels: documentation

#3014 [Documentation] Add missing default extension points
  www/content/extensions/building.md
Labels: documentation

#3015 Fix wrong cursor style in webring
  www/content/webring.md
Labels: website

#3017 Add missing disableInheritance documentation
  www/content/api.md
  www/content/attributes/hx-inherit.md
  www/content/reference.md
Labels: documentation

#3018 Add web components essay
  www/content/essays/_index.md
  www/content/essays/webcomponents-work-great.md
Labels: website

#3006 fix vertical alignment of github stars button in all states
  www/themes/htmx-theme/static/css/site.css
  www/themes/htmx-theme/templates/base.html
Labels: website, ready for review

#3021 WC essay typo fixes
  www/content/essays/webcomponents-work-great.md
Labels: website

#3022 [Documentation] Fix incorrect link
  www/content/events.md
Labels: documentation

#3024 [Documentation] Add missing htmx:sendAbort event
  www/content/events.md
  www/content/reference.md
Labels: documentation

#3030 typing for `defineExtension` should allow partials
  src/htmx.js
Labels: bug, documentation

#3007 Improve detail.elt event documentation
  www/content/events.md
Labels: documentation, ready for review

#3036 feat: add amz-content-sha256 extension to docs
  www/content/extensions/_index.md
Labels: documentation, extension

#3051 [Documentation] Fix outdated attribute links
  www/content/extensions/response-targets.md
  www/content/extensions/sse.md
Labels: documentation
