Repository bigskysoftware/htmx, pull requests merged in 2024-10, with the labels that each got.

#2934 enable hx-preserve handing for oob swaps
  src/htmx.js
  test/attributes/hx-preserve.js
  www/content/attributes/hx-preserve.md
Labels: bug, ready for review

#2933 fix #2932: check parent is null for swap delete
  src/htmx.js
  test/core/api.js
Labels: bug, ready for review

#2891 Change hx-trigger's changed modifier to work for independent trigger specifications
  src/htmx.js
  test/attributes/hx-trigger.js
Labels: bug, ready for review

#2878 fix htmx.ajax defaulting to swap body when target not found
  src/htmx.js
  test/core/api.js
Labels: bug, ready for review

#2585 Allow non-id selectors in `hx-select-oob` to fix #2561
  src/htmx.js
  test/attributes/hx-select-oob.js
Labels: bug, ready for review, 1.0

#2781 Optimize Head regex
  src/htmx.js
  test/manual/hxboost_partial_template_parsing/index.html
Labels: ready for review, performance

#2799 :bug: Prevents erroring on null vals
  src/htmx.js
  test/attributes/hx-vals.js
  test/core/parameters.js
Labels: bug, ready for review, 2.0

#2823 remove extra hx-swap-oob attribute that is not used in the page
  src/htmx.js
  test/attributes/hx-swap-oob.js
Labels: enhancement, ready for review

#2860 [FIX] Properly remove request indicators
  src/htmx.js
Labels: bug, ready for review

#2802 Better graceful degradation of boosted form element
  src/htmx.js
  test/attributes/hx-boost.js
Labels: bug, ready for review

#2846 fix for hx-swab-oob within web components
  src/htmx.js
  test/attributes/hx-swap-oob.js
Labels: bug, ready for review

#2866 Add shadowRoot host selector
  src/htmx.js
  test/core/shadowdom.js
Labels: bug, ready for review

#2914 Clarify event filter uses in hx-trigger
  www/content/attributes/hx-trigger.md
Labels: documentation

#2943 Fix typos in docs
  www/content/essays/htmx-sucks.md
  www/content/essays/interviews/henning_koch.md
  www/content/essays/is-htmx-another-javascript-framework.md
  www/content/essays/rest-explained.md
  www/content/extensions/htmx-1-compat.md
  www/content/extensions/idiomorph.md
  www/content/extensions/sse.md
  www/content/headers/hx-trigger.md
  www/themes/htmx-theme/highlighting/two-dark-edited.tmTheme
Labels: documentation

#2722 Add htmx4s to scala server-examples
  www/content/server-examples.md
Labels: documentation

#2949 improve hx-preserve documentation
  www/content/attributes/hx-preserve.md
Labels: documentation

#2950 Correct lint command in contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#2964 Use correct extended CSS selector name in hx-trigger notes section
  www/content/attributes/hx-trigger.md
Labels: documentation

#2955 docs: migrate realtime server implementation
  test/ws-sse/README.md
  test/ws-sse/server.mjs
  test/ws-sse/static/black_transparent.svg
  test/ws-sse/static/data.json
  test/ws-sse/static/index.html
  test/ws-sse/static/site-base.html
  test/ws-sse/static/sse-about.html
  test/ws-sse/static/sse-multichannel-ext.html
  test/ws-sse/static/sse-multiple-ext.html
  test/ws-sse/static/sse-settle-ext.html
  test/ws-sse/static/sse-simple-ext.html
  test/ws-sse/static/sse-target-ext.html
  test/ws-sse/static/sse-triggers-ext.html
  test/ws-sse/static/stylesheet.css
  test/ws-sse/static/white_transparent.svg
  test/ws-sse/static/ws-about.html
  test/ws-sse/static/ws-echo-ext.html
  test/ws-sse/static/ws-heartbeat-ext.html
  test/ws-sse/static/ws-reconnect-ext.html
Labels: documentation

#2970 Add link to contact-app built in Blazor
  www/content/server-examples.md
Labels: documentation

#2967 Fix TypeError on null path variable
  src/htmx.js
  test/attributes/hx-boost.js
Labels: bug, ready for review

#2948 ajax helper with no source or target defaults to body
  src/htmx.js
  test/core/api.js
Labels: bug, ready for review

#2977 Add missing word in previous CSS selector documentation
  www/content/docs.md
Labels: documentation

#2980 "Download a Copy" in the doc points to old release 2.0.2; this PR changes it to 2.0.3 as it should be
  www/content/docs.md
Labels: documentation

#2981 Fix link to no-cache extension readme
  www/content/extensions/_index.md
Labels: documentation

#2983 Fix typo on extensions page
  www/content/extensions/_index.md
Labels: documentation

#2984 docs: Fix typo
  www/content/docs.md
Labels: documentation

#2988 Fixing a typo in confirm.md
  www/content/examples/confirm.md
Labels: documentation
