Repository bigskysoftware/htmx, pull requests merged in 2024-09, with the labels that each got.

#2861 Fix focusin-based tests
  test/core/parameters.js
Labels: bug, ready for review, devops

#2862 Trivial grammar fixes
  www/content/docs.md
Labels: documentation

#2875 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2881 Update hx-select.md
  www/content/attributes/hx-select.md
Labels: documentation

#2882 Documentation of svg oob swaps
  www/content/attributes/hx-swap-oob.md
Labels: documentation

#2898 Documentation for dynamic hx-vals
  test/attributes/hx-vals.js
  www/content/attributes/hx-vals.md
Labels: documentation

#2904 Documentation 3xx redirects can't send headers
  www/content/docs.md
  www/content/headers/hx-location.md
  www/content/headers/hx-push-url.md
  www/content/headers/hx-redirect.md
  www/content/headers/hx-replace-url.md
  www/content/headers/hx-trigger.md
  www/content/reference.md
Labels: documentation

#2911 [Documentation] Config default update for methodsThatUseUrlParams
  www/content/api.md
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#2889 [Documentartion]Add more information about other swap strategies
  www/content/attributes/hx-swap-oob.md
Labels: documentation

#2918 Fix docs for `htmx.config.scrollBehavior`
  www/content/api.md
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#2886 add F# server-examples
  www/content/server-examples.md
Labels: documentation, ready for review

#2929 Added htmx before transition reference link
  www/content/reference.md
Labels: documentation

#2926 Improved documentation for htmx:confirm event and examples for implementing sweetalert
  www/content/events.md
  www/content/examples/confirm.md
Labels: documentation

#2930 Add a link to the extensions site on the docs page
  www/content/docs.md
Labels: documentation

#2925 [bug] load trigger stops hx-disabled-elt getting re-enabled
  src/htmx.js
  test/attributes/hx-disabled-elt.js
Labels: bug, ready for review

#2903 Handle Space before comma in Trigger Spec
  src/htmx.js
  test/attributes/hx-trigger.js
Labels: bug, ready for review
