Repository bigskysoftware/htmx, pull requests merged in 2024-12, with the labels that each got.

#3064 Handle Invalid template content
  src/htmx.js
Labels: bug, ready for review

#3034 Make bodyContains return true for nested shadow roots
  src/htmx.js
Labels: ready for review

#3033 Add missing htmx:trigger event on load triggers
  src/htmx.js
  test/attributes/hx-trigger.js
Labels: ready for review

#2976 Do not execute hx-trigger="load" on re-initialization of an existing node
  src/htmx.js
  test/core/api.js
Labels: bug, ready for review

#2951 Replace deprecated String.prototype.substr usage
  src/htmx.js
Labels: ready for review

#3012 Add http4k server example
  www/content/server-examples.md
Labels: documentation

#2902 Support multiple extended selectors for hx-include, hx-trigger from, and hx-disabled-elt
  src/htmx.js
  test/attributes/hx-boost.js
  test/attributes/hx-disabled-elt.js
  test/attributes/hx-include.js
  test/attributes/hx-trigger.js
Labels: enhancement, ready for review

#3076 Update hx-trigger.md
  www/content/attributes/hx-trigger.md
Labels: documentation

#3001 Update preload extension documentation: form preloading and preload="always"
  www/content/extensions/preload.md
Labels: documentation, extension

#2229 Improve active-search example by not using chrome-only event "search"
  www/content/examples/active-search.md
Labels: documentation

#2474 Add reference to hx-preserve to the example at "Preserving File Inputs after Form Errors"
  www/content/examples/file-upload-input.md
Labels: documentation

#3047 Docs anchors
  www/content/_index.md
  www/content/docs.md
  www/content/essays/_index.md
  www/content/examples/_index.md
  www/content/examples/move-before/_index.md
  www/themes/htmx-theme/static/css/site.css
Labels: documentation, website
