Repository bigskysoftware/htmx, pull requests merged in 2024-03, with the labels that each got.

#2363 [Documentation] Server Examples: Add F# - Giraffe example
  www/content/server-examples.md
Labels: documentation

#2345 Add Recipya to the webring
  www/content/webring.md
Labels: website

#2327 [DOC] clarify SSE hx-swap docs to note #784
  www/content/extensions/server-sent-events.md
Labels: documentation

#1235 Add config option to ignore nested oob-swaps instead of processing them
  src/htmx.js
  test/attributes/hx-swap-oob.js
  www/content/attributes/hx-swap-oob.md
  www/content/docs.md
  www/content/reference.md
Labels: enhancement, under discussion

#2261 Fix TypeScript types
  src/htmx.d.ts
Labels: bug

#2365 Double script exec tests variants using templates: issue confirmed
  test/core/regressions.js
Labels: bug

#2391 WS.js fix for Safari on iOS 17.4
  src/ext/sse.js
  src/ext/ws.js
Labels: bug

#2408 Fix IE11 incompatibilities
  src/htmx.js
  test/core/ajax.js
  test/core/regressions.js
Labels: bug

#2413 Link to section on CSS Transitions instead of Mozilla page
  www/content/docs.md
Labels: documentation

#2409 Fix example for mustache in client-side-templates extension.
  www/content/extensions/client-side-templates.md
Labels: documentation
