Repository bigskysoftware/htmx, pull requests merged in 2024-07, with the labels that each got.

#2701 HtmxAjaxHelperContext typedef should have all optional fields
  src/htmx.d.ts
  src/htmx.js
  www/content/api.md
Labels: documentation

#2700 #41540 Update Quarkus with recent examples
  www/content/server-examples.md
Labels: documentation

#2696 Clarify that hx-trigger:from doesn't dynamically update
  www/config.toml
  www/content/attributes/hx-trigger.md
  www/content/docs.md
Labels: documentation

#2695 Added a FastAPI + TailwindCSS + DaisyUI example
  www/content/server-examples.md
Labels: documentation

#2708 Let templates have plaintext as contents (fixes 2702)
  src/htmx.js
Labels: bug, ready for review, 2.0

#2716 Correct hx-delete doc-url to https://htmx.org/attributes/hx-delete/
  editors/jetbrains/htmx.web-types.json
Labels: documentation

#2719 fix: example buttons in darkmode
  www/content/examples/click-to-edit.md
Labels: website

#2721 fix: type definitions for HtmxExtension
  src/htmx.d.ts
  src/htmx.js
Labels: documentation, 2.0

#2729 Fix default `scrollBehavior` value in docs
  src/htmx.js
  www/content/reference.md
Labels: documentation

#2732 Update README.md - fix url to htmx extensions
  README.md
Labels: documentation

#2749 Fix: values order with non-GET requests
  src/htmx.js
  test/core/parameters.js
Labels: bug, ready for review, 2.0

#2748 Fix: stringify objects when appending them to FormData
  src/htmx.js
Labels: bug, ready for review, 2.0

#2551 docs: update jetbrains sponsor logo
  www/content/_index.md
  www/static/img/jetbrains.png
  www/static/img/jetbrains.svg
Labels: documentation
