Repository bigskysoftware/htmx, pull requests merged in 2024-08, with the labels that each got.

#2783 Fix typo in update-other-content.md
  www/content/examples/update-other-content.md
Labels: documentation

#2785 Fix inlineStyleNonce typo in reference
  www/content/reference.md
Labels: documentation

#2778 Fix file upload through htmx.ajax
  src/htmx.js
  test/core/parameters.js
Labels: bug, ready for review, 2.0

#2752 Do not boost forms with method="dialog"
  src/htmx.js
  test/attributes/hx-boost.js
Labels: bug, ready for review

#2715 Fix example for responseHandling config via <meta> tag
  www/content/docs.md
Labels: documentation, ready for review

#2411 fix: Fire htmx:trigger event on delayed triggers
  src/htmx.js
  test/attributes/hx-trigger.js
Labels: bug, ready for review

#2795 Update CONTRIBUTING.md - fixing a link, wording
  CONTRIBUTING.md
Labels: documentation

#2793 Add HTML comment and catch-all to responseHandling config via <meta> tag
  www/content/docs.md
Labels: documentation

#2791 Update installing download link to v2
  www/content/docs.md
Labels: documentation

#2809 Fix typo in update-other-content.md
  www/content/examples/update-other-content.md
Labels: documentation

#2814 fix cdn typo
  www/content/docs.md
Labels: documentation

#2820 docs: add missing semicolons
  www/content/attributes/hx-indicator.md
Labels: documentation

#2821 fix responseHandling meta example
  www/content/docs.md
Labels: documentation

#2826 Update lazy-load.md
  www/content/examples/lazy-load.md
Labels: documentation

#2827 Update server-examples.md
  www/content/server-examples.md
Labels: documentation

#2792 Link to htmx:sendError from error description
  www/content/docs.md
Labels: documentation

#2842 Redirect /extensions to extensions website
  www/content/extensions/_index.md
Labels: website

#2853 Upgrade Typescript to move configuration from const to let
  dist/htmx.esm.d.ts
  package-lock.json
  package.json
  src/htmx.d.ts
  src/htmx.js
Labels: bug, ready for review

#2841 fix restoreHistory title replacment
  src/htmx.js
Labels: bug, ready for review

#2836 Ability to add `options` argument to event listener
  src/htmx.js
  test/core/events.js
  www/content/api.md
Labels: enhancement, ready for review

#2780 Listen to resize events and check revealed
  src/htmx.js
Labels: bug, ready for review
