Repository bigskysoftware/htmx, pull requests merged in 2024-04, with the labels that each got.

#2481 Fix #2317 force conversion to FormData for xhr.send
  src/htmx.js
Labels: bug

#2500 Update podcasts.csv
  www/content/talk/podcasts.csv
Labels: documentation

#2506 Add Statusnook to the webring
  www/content/webring.md
Labels: documentation

#2494 Remove Node 15 requirement mention from README
  README.md
Labels: documentation, 2.0

#2471 use same ID throughout the example
  www/content/essays/rest-explained.md
Labels: documentation

#2444 Update hx-indicator.md
  www/content/attributes/hx-indicator.md
Labels: documentation

#2443 Update confirm.md
  www/content/examples/confirm.md
Labels: documentation

#2436 Fix a trivial typo in CONTRIBUTING.md.
  CONTRIBUTING.md
Labels: documentation

#2405 fix(docs): Add missing apostrophes
  www/content/docs.md
Labels: documentation

#2404 docs: aria-selected true in Tabs HATEOS example
  www/content/examples/tabs-hateoas.md
Labels: documentation

#2376 More explicit explanation of htmx.config.getCacheBusterParam
  src/htmx.d.ts
  www/content/api.md
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#2373 docs: fix `this` binding in `onClick .then` handler with arrow function
  www/content/examples/confirm.md
Labels: documentation

#2505 [2.0] Improve extension registration logic
  src/htmx.d.ts
  src/htmx.js
Labels: enhancement, extension, 2.0
