Repository bigskysoftware/htmx, pull requests merged in 2025-07, with the labels that each got.

#3341 Bugfix: swap="outerHTML" on <div> with style attribute leaves htmx-swapping class behind
  src/htmx.js
  test/core/regressions.js
Labels: bug, ready for review

#3344 Fix variable names
  TESTING.md
  editors/jetbrains/htmx.web-types.json
  test/attributes/hx-swap-oob.js
  www/content/_index.md
  www/content/events.md
  www/static/test/attributes/hx-swap-oob.js
Labels: ready for review

#3361 update indicator style to have visibility:hidden for screen readers
  src/htmx.js
  www/content/attributes/hx-indicator.md
Labels: ready for review

#3364 Added extension
  www/content/extensions/_index.md
Labels: website

#3359 Update Rust server examples with actix-htmx
  www/content/server-examples.md
Labels: website

#3358 Remove redundant script tags
  www/content/examples/modal-custom.md
  www/content/examples/modal-uikit.md
  www/content/examples/tabs-javascript.md
Labels: website

#3209 Fix google search syntax from search bar
  www/themes/htmx-theme/templates/base.html
Labels: website

#3372 implement reportValidity for reporting proper form validation errors behind config flag
  src/htmx.js
  test/core/validation.js
  www/content/api.md
  www/content/docs.md
  www/content/events.md
  www/content/reference.md
Labels: ready for review

#3073 Fix ajax api body test
  test/core/api.js
Labels: bug
