Repository bigskysoftware/htmx, pull requests merged in 2025-01, with the labels that each got.

#2939 Add an example of evaluated values passed to hx-headers.
  www/content/attributes/hx-headers.md
Labels: documentation

#3090 Update docs.md to fix dead link
  www/content/docs.md
Labels: documentation

#3095 fix QUIRKS.md typo
  www/content/QUIRKS.md
Labels: documentation

#3100 Add example for form reset pattern
  www/content/docs.md
  www/content/examples/_index.md
  www/content/examples/reset-user-input.md
Labels: documentation

#3105 Add 404 page
  www/templates/404.html
  www/themes/htmx-theme/templates/base.html
Labels: website

#3098 Fix error in quirks documentation for htmx config
  www/content/QUIRKS.md
Labels: documentation

#3110 [Documentation] Make htmx:beforeSwap more complete
  www/content/events.md
Labels: documentation

#3111 Fix broken docs links on quirks page
  www/content/QUIRKS.md
Labels: documentation

#3094 Properly resolve referenced forms.
  CHANGELOG.md
  src/htmx.js
  test/core/ajax.js
  test/core/internals.js
  www/content/docs.md
Labels: bug

#3075 Enforce no-op on submit buttons with formmethod=dialog.
  CHANGELOG.md
  src/htmx.js
  test/core/ajax.js
  test/core/shadowdom.js
Labels: bug

#3123 Fix htmx:beforeHistorySave docs
  www/content/events.md
Labels: documentation

#3124 Fixed TwinSpark link in alternatives
  www/content/essays/alternatives.md
Labels: documentation

#3109 Adding example to hx-ext documentation
  www/content/attributes/hx-ext.md
Labels: documentation

#3147 Extension Proposal: `hx-drag` for `dragstart` & `drop` triggered htmx requests.
  www/content/extensions/_index.md
Labels: documentation, extension

#3154 Essay descriptions
  www/content/essays/10-tips-for-SSR-HDA-apps.md
  www/content/essays/a-real-world-nextjs-to-htmx-port.md
  www/content/essays/a-real-world-react-to-htmx-port.md
  www/content/essays/a-real-world-wasm-to-htmx-port.md
  www/content/essays/a-response-to-rich-harris.md
  www/content/essays/alternatives.md
  www/content/essays/another-real-world-react-to-htmx-port.md
  www/content/essays/architectural-sympathy.md
  www/content/essays/codin-dirty.md
  www/content/essays/complexity-budget.md
  www/content/essays/does-hypermedia-scale.md
  www/content/essays/future.md
  www/content/essays/hateoas.md
  www/content/essays/how-did-rest-come-to-mean-the-opposite-of-rest.md
  www/content/essays/htmx-sucks.md
  www/content/essays/hypermedia-apis-vs-data-apis.md
  www/content/essays/hypermedia-clients.md
  www/content/essays/hypermedia-driven-applications.md
  www/content/essays/hypermedia-friendly-scripting.md
  www/content/essays/hypermedia-on-whatever-youd-like.md
  www/content/essays/interviews/chris_wanstrath.md
  www/content/essays/interviews/henning_koch.md
  www/content/essays/interviews/makinde_adeagbo.md
  www/content/essays/interviews/mike_amundsen.md
  www/content/essays/is-htmx-another-javascript-framework.md
  www/content/essays/locality-of-behaviour.md
  www/content/essays/lore.md
  www/content/essays/mvc.md
  www/content/essays/no-build-step.md
  www/content/essays/prefer-if-statements.md
  www/content/essays/rest-copypasta.md
  www/content/essays/rest-explained.md
  www/content/essays/right-click-view-source.md
  www/content/essays/spa-alternative.md
  www/content/essays/splitting-your-apis.md
  www/content/essays/template-fragments.md
  www/content/essays/two-approaches-to-decoupling.md
  www/content/essays/vendoring.md
  www/content/essays/view-transitions.md
  www/content/essays/web-security-basics-with-htmx.md
  www/content/essays/webcomponents-work-great.md
  www/content/essays/when-to-use-hypermedia.md
  www/content/essays/why-gumroad-didnt-choose-htmx.md
  www/content/essays/why-tend-not-to-use-content-negotiation.md
  www/content/essays/you-cant.md
  www/templates/demo.html
  www/themes/htmx-theme/templates/essay.html
  www/themes/htmx-theme/templates/page.html
Labels: documentation

#3159 Fix some external links
  www/content/essays/vendoring.md
  www/content/essays/view-transitions.md
Labels: documentation

#3160 Fix some external links (#3157)
  www/content/extensions/_index.md
Labels: documentation, extension
