Repository bigskysoftware/htmx, pull requests merged in 2025-04, with the labels that each got.

#3259 docs: Add dynamic-url to community extensions list
  www/content/extensions/_index.md
Labels: documentation, extension

#3262 fix customized confirmation example
  www/content/examples/confirm.md
Labels: documentation

#3260 Docs - add sections and search filtering for community extensions
  www/content/extensions/_index.md
  www/templates/shortcodes/markdown.md
  www/themes/htmx-theme/static/css/site.css
  www/themes/htmx-theme/static/js/_hyperscript.js
  www/themes/htmx-theme/templates/base.html
Labels: documentation

#3274 Mention hx-include does not match disabled fields. Fixes #3053
  www/content/attributes/hx-include.md
Labels: documentation

#3273 Update testing framework to web-test-runner and improve code coverage
  .gitignore
  TESTING.md
  package-lock.json
  package.json
  test/attributes/hx-boost.js
  test/attributes/hx-confirm.js
  test/attributes/hx-ext.js
  test/attributes/hx-get.js
  test/attributes/hx-headers.js
  test/attributes/hx-include.js
  test/attributes/hx-preserve.js
  test/attributes/hx-prompt.js
  test/attributes/hx-push-url.js
  test/attributes/hx-replace-url.js
  test/attributes/hx-request.js
  test/attributes/hx-swap-oob.js
  test/attributes/hx-swap.js
  test/attributes/hx-trigger.js
  test/attributes/hx-vals.js
  test/core/ajax.js
  test/core/api.js
  test/core/config.js
  test/core/extensions.js
  test/core/headers.js
  test/core/internals.js
  test/core/parameters.js
  test/core/perf.js
  test/core/security.js
  test/core/tokenizer.js
  test/index.html
  web-test-runner.config.mjs
Labels: devops

#3279 Documentation update for events
  www/content/events.md
Labels: documentation

#3280 Adjust examples
  www/content/examples/bulk-update.md
  www/content/examples/edit-row.md
Labels: documentation

#3281 Docs: Update Link
  www/content/extensions/_index.md
Labels: documentation

#3284 handle removing request lock on errors
  src/htmx.js
  test/core/api.js
  test/core/headers.js
  test/core/security.js
Labels: bug, ready for review

#3282 Additional Code Coverage
  src/htmx.js
  test/attributes/hx-include.js
  test/core/api.js
  test/core/parameters.js
  test/core/security.js
  web-test-runner.config.mjs
Labels: enhancement, ready for review, devops

#3283 proxy window.location for testing and extension overrides
  src/htmx.js
  test/attributes/hx-push-url.js
  test/core/headers.js
Labels: enhancement, ready for review, devops

#3277 Remove old IE support
  src/htmx.js
  test/attributes/hx-push-url.js
Labels: ready for review, 2.0

#3074 Get rid of latest usages of substr
  src/htmx.js
  test/util/util.js
Labels: ready for review

#3173 Write title as innerText instead of innerHTML
  src/htmx.js
Labels: enhancement, ready for review

#3196 Fix event not being available in hx-vals/hx-vars when hx-trigger has delay
  src/htmx.js
  test/attributes/hx-vals.js
Labels: bug, ready for review

#3278 Add historyRestoreAsHxRequest config to optionally disable hx-request header from history restore requests
  src/htmx.js
  test/core/headers.js
  www/content/api.md
  www/content/docs.md
  www/content/reference.md
Labels: enhancement

#3294 Fix typo
  src/htmx.js
  www/content/api.md
  www/content/docs.md
  www/content/reference.md
Labels: documentation

#3295 Add substr lint
  package.json
Labels: devops

#3296 Correction for confirm example
  www/content/examples/confirm.md
Labels: documentation
