Repository bigskysoftware/htmx, pull requests merged in 2025-06, with the labels that each got.

#3315 Fix missing TypeScript property
  src/htmx.js
Labels: documentation, enhancement, ready for review

#3304 Fixes issue 1537 - OOB does not escape query selector - updated version
  src/htmx.js
  test/attributes/hx-swap-oob.js
Labels: bug, ready for review

#3195 Feature: add extensionsToIgnore to withExtensions
  src/htmx.js
Labels: enhancement, ready for review

#3188 Typo in addEventListener - use evt instead of event
  src/htmx.js
Labels: ready for review

#3178 Fix target value in htmx:targetError when inheritance has been used
  src/htmx.js
  test/core/events.js
Labels: bug, ready for review

#3153 Feat/hx reselect support unset
  src/htmx.js
  test/core/headers.js
Labels: enhancement, ready for review

#1766 Inherit list-keyword in hx-include / hx-indicator
  src/htmx.js
  test/attributes/hx-include.js
  test/attributes/hx-indicator.js
Labels: enhancement, ready for review

#3208 Remove obsolete npm command + fix links to ws/sse extensions
  README.md
  package.json
Labels: documentation

#3357 fix click events on elements wrapped by link don't cancel link navigation
  src/htmx.js
  test/core/internals.js
  test/core/regressions.js
Labels: bug
